server:
  port: 8089
  servlet:
    context-path: /

#??mysql????????????
spring:
  datasource:
    username: root
    password: SBdaowodehao24
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dlyk?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true

  #??redis?????
  data:
    redis:
      host: 192.168.64.128
      port: 6379
      password:
      database: 0

  #?spring??bean?????, BeanA ?? BeanB???BeanB???BeanA????????
  main:
    allow-circular-references: true

  #??????json?????????????
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

#??mapper.xml???????
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #??mybatis????sql?????sql????????
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#???????????
logging:
  level:
    root: info

